### PR TITLE
revert back wpa_supplicant.conf

### PR DESCRIPTION
**Pull request by knone1**
because its not working to search wifi

### CODE REVIEW

**Comment by crpalmer** [comment]
Try this commit instead:

ae3d90e mofd-common: Fix wpa_supplicant.conf derp

**Comment by knone1** [comment]
ok ok i change now thanks

**Comment by crpalmer** [comment]
Does that new commit fix it for you?  Apparently my normal usage is not
affected by not having the conf so I don't trust my testing that the new
version is really fixed... :-)

**Comment by knone1** [comment]
yes in resurrection rom i test the build if without .conf the wifi is not working to scan so i try to place again the .conf file and reboot it fix the scan and show available wifi spot

**Pull request closed without merging**
