### PR TITLE
ril class allow us to switch sim1 and sm2 ON/OFF

### PR DESCRIPTION
**Pull request by knone1**
the rild is switching dsda <> dsda but there a problem in signal icon it always showing 2 signal icon even sim 1/2 are off
heres the demo https://www.youtube.com/watch?v=os0v8TT5Kpc

### CODE REVIEW

**Comment by crpalmer** [comment]
I pulled this commit and it doesn't seem to actually disable the sim even though the UI (in Settings) does show a sim as being disabled.

To test, I disabled SIM1 and then I used SIM2 to call SIM1 and the call went through (even though Settings says it is disabled).

**Comment by knone1** [comment]
yes i think just only ui say the sim is disable but wok in call if we disable the sim 1 only sim2 is allowed to call not tested on text if sim 1 will receive a sms message still a bug thanks we hope we can improve soon i really love cyanogenmod rom for my android devices

**Comment by crpalmer** [comment]
FYI, I think that this was fixing part of the problem, but still missing things (probably talking to the modem to actually disable it?).

**Comment by knone1** [comment]
yes i think there something missing in code , or try to recode the init.modem.rc for switching rild that fits to cyanogenmod rom . and also clean up the proprietary/etc/catalog remove some init prop for setting multisim that base on stock asus rom

**Pull request closed without merging**
